CREATE TABLE `review` (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    username VARCHAR(50) NOT NULL DEFAULT '',
    product_id INT UNSIGNED NOT NULL,
    product_name VARCHAR(50) NOT NULL DEFAULT '',
    product_specification VARCHAR(100) NOT NULL DEFAULT '',
    general_review VARCHAR(50) NOT NULL DEFAULT '',
    detailed_review VARCHAR(1000) NOT NULL DEFAULT '',
    rating INT UNSIGNED NOT NULL DEFAULT 1 ,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);